//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
// See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.10 at 05:15:57 PM HKT 
//


package icao.iwxxm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AerodromeSeaConditionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AerodromeSeaConditionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="seaSurfaceTemperature" type="{http://icao.int/iwxxm/2021-2}MeasureWithNilReasonType"/&gt;
 *         &lt;element name="significantWaveHeight" type="{http://icao.int/iwxxm/2021-2}DistanceWithNilReasonType" minOccurs="0"/&gt;
 *         &lt;element name="seaState" type="{http://icao.int/iwxxm/2021-2}SeaSurfaceStateType" minOccurs="0"/&gt;
 *         &lt;element name="extension" type="{http://icao.int/iwxxm/2021-2}ExtensionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AerodromeSeaConditionType", propOrder = {
    "seaSurfaceTemperature",
    "significantWaveHeight",
    "seaState",
    "extension"
})
public class AerodromeSeaConditionType {

    @XmlElement(required = true, nillable = true)
    protected MeasureWithNilReasonType seaSurfaceTemperature;
    @XmlElementRef(name = "significantWaveHeight", namespace = "http://icao.int/iwxxm/2021-2", type = JAXBElement.class, required = false)
    protected JAXBElement<DistanceWithNilReasonType> significantWaveHeight;
    @XmlElementRef(name = "seaState", namespace = "http://icao.int/iwxxm/2021-2", type = JAXBElement.class, required = false)
    protected JAXBElement<SeaSurfaceStateType> seaState;
    protected List<ExtensionType> extension;

    /**
     * Gets the value of the seaSurfaceTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureWithNilReasonType }
     *     
     */
    public MeasureWithNilReasonType getSeaSurfaceTemperature() {
        return seaSurfaceTemperature;
    }

    /**
     * Sets the value of the seaSurfaceTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureWithNilReasonType }
     *     
     */
    public void setSeaSurfaceTemperature(MeasureWithNilReasonType value) {
        this.seaSurfaceTemperature = value;
    }

    /**
     * Gets the value of the significantWaveHeight property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DistanceWithNilReasonType }{@code >}
     *     
     */
    public JAXBElement<DistanceWithNilReasonType> getSignificantWaveHeight() {
        return significantWaveHeight;
    }

    /**
     * Sets the value of the significantWaveHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DistanceWithNilReasonType }{@code >}
     *     
     */
    public void setSignificantWaveHeight(JAXBElement<DistanceWithNilReasonType> value) {
        this.significantWaveHeight = value;
    }

    /**
     * Gets the value of the seaState property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SeaSurfaceStateType }{@code >}
     *     
     */
    public JAXBElement<SeaSurfaceStateType> getSeaState() {
        return seaState;
    }

    /**
     * Sets the value of the seaState property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SeaSurfaceStateType }{@code >}
     *     
     */
    public void setSeaState(JAXBElement<SeaSurfaceStateType> value) {
        this.seaState = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionType }
     * 
     * 
     */
    public List<ExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<ExtensionType>();
        }
        return this.extension;
    }

}
