//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
// See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.10 at 05:15:57 PM HKT 
//


package icao.iwxxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml.AbstractGMLType;
import net.opengis.gml.TimeInstantPropertyType;


/**
 * <p>Java class for RadiationIncidentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RadiationIncidentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractGMLType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="siteName" type="{http://icao.int/iwxxm/2021-2}StringWithNilReasonType"/&gt;
 *         &lt;element name="incidentTime" type="{http://www.opengis.net/gml/3.2}TimeInstantPropertyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RadiationIncidentType", propOrder = {
    "siteName",
    "incidentTime"
})
public class RadiationIncidentType
    extends AbstractGMLType
{

    @XmlElement(required = true, nillable = true)
    protected StringWithNilReasonType siteName;
    @XmlElement(required = true)
    protected TimeInstantPropertyType incidentTime;

    /**
     * Gets the value of the siteName property.
     * 
     * @return
     *     possible object is
     *     {@link StringWithNilReasonType }
     *     
     */
    public StringWithNilReasonType getSiteName() {
        return siteName;
    }

    /**
     * Sets the value of the siteName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringWithNilReasonType }
     *     
     */
    public void setSiteName(StringWithNilReasonType value) {
        this.siteName = value;
    }

    /**
     * Gets the value of the incidentTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeInstantPropertyType }
     *     
     */
    public TimeInstantPropertyType getIncidentTime() {
        return incidentTime;
    }

    /**
     * Sets the value of the incidentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeInstantPropertyType }
     *     
     */
    public void setIncidentTime(TimeInstantPropertyType value) {
        this.incidentTime = value;
    }

}
