//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
// See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.10 at 05:15:57 PM HKT 
//


package icao.iwxxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://icao.int/iwxxm/2021-2}BasicReportType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="translatedBulletinID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="translatedBulletinReceptionTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="translationCentreDesignator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="translationCentreName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="translationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="translationFailedTAC" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportType")
@XmlSeeAlso({
    SpaceWeatherAdvisoryType.class,
    VolcanicAshAdvisoryType.class,
    TropicalCycloneAdvisoryType.class,
    AIRMETType.class,
    SIGMETType.class,
    TAFType.class,
    MeteorologicalAerodromeObservationReportType.class
})
public abstract class ReportType
    extends BasicReportType
{

    @XmlAttribute(name = "translatedBulletinID")
    protected String translatedBulletinID;
    @XmlAttribute(name = "translatedBulletinReceptionTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar translatedBulletinReceptionTime;
    @XmlAttribute(name = "translationCentreDesignator")
    protected String translationCentreDesignator;
    @XmlAttribute(name = "translationCentreName")
    protected String translationCentreName;
    @XmlAttribute(name = "translationTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar translationTime;
    @XmlAttribute(name = "translationFailedTAC")
    protected String translationFailedTAC;

    /**
     * Gets the value of the translatedBulletinID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranslatedBulletinID() {
        return translatedBulletinID;
    }

    /**
     * Sets the value of the translatedBulletinID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranslatedBulletinID(String value) {
        this.translatedBulletinID = value;
    }

    /**
     * Gets the value of the translatedBulletinReceptionTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTranslatedBulletinReceptionTime() {
        return translatedBulletinReceptionTime;
    }

    /**
     * Sets the value of the translatedBulletinReceptionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTranslatedBulletinReceptionTime(XMLGregorianCalendar value) {
        this.translatedBulletinReceptionTime = value;
    }

    /**
     * Gets the value of the translationCentreDesignator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranslationCentreDesignator() {
        return translationCentreDesignator;
    }

    /**
     * Sets the value of the translationCentreDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranslationCentreDesignator(String value) {
        this.translationCentreDesignator = value;
    }

    /**
     * Gets the value of the translationCentreName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranslationCentreName() {
        return translationCentreName;
    }

    /**
     * Sets the value of the translationCentreName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranslationCentreName(String value) {
        this.translationCentreName = value;
    }

    /**
     * Gets the value of the translationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTranslationTime() {
        return translationTime;
    }

    /**
     * Sets the value of the translationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTranslationTime(XMLGregorianCalendar value) {
        this.translationTime = value;
    }

    /**
     * Gets the value of the translationFailedTAC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranslationFailedTAC() {
        return translationFailedTAC;
    }

    /**
     * Sets the value of the translationFailedTAC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranslationFailedTAC(String value) {
        this.translationFailedTAC = value;
    }

}
