//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
// See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.10 at 05:15:57 PM HKT 
//


package icao.iwxxm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrendForecastTimeIndicatorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TrendForecastTimeIndicatorType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AT"/&gt;
 *     &lt;enumeration value="UNTIL"/&gt;
 *     &lt;enumeration value="FROM"/&gt;
 *     &lt;enumeration value="FROM_UNTIL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TrendForecastTimeIndicatorType")
@XmlEnum
public enum TrendForecastTimeIndicatorType {


    /**
     * This trend forecast specifies a time instant at which time conditions occur (AT)
     * 
     */
    AT,

    /**
     * This trend forecast specifies a time period which commences at the beginning of the trend forecast period and is completed by a specified time (TL)
     * 
     */
    UNTIL,

    /**
     * This trend forecast specifies a time period which commences at a specified time and is completed by the end of the trend forecast period (FM)
     * 
     */
    FROM,

    /**
     * This trend forecast specifies a time period which commences at a specified time and is completed by another specified time (FM and TL)
     * 
     */
    FROM_UNTIL;

    public String value() {
        return name();
    }

    public static TrendForecastTimeIndicatorType fromValue(String v) {
        return valueOf(v);
    }

}
