//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-SNAPSHOT 
// See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.19 at 10:49:53 AM HKT 
//


package icao.iwxxm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TropicalCycloneMovementType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TropicalCycloneMovementType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MOVING"/&gt;
 *     &lt;enumeration value="MOVING_SLOWLY"/&gt;
 *     &lt;enumeration value="STATIONARY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "TropicalCycloneMovementType")
@XmlEnum
public enum TropicalCycloneMovementType {


    /**
     * The tropical cyclone is moving and will be reported with the associated movement speed and direction
     * 
     */
    MOVING,

    /**
     * The tropical cyclone is moving slowly (< 6 km/h or 3 kt) and will not have a reported movement speed or direction
     * 
     */
    MOVING_SLOWLY,

    /**
     * The tropical cyclone is stationary (< 2 km/h or 1 kt) and will not have a reported movement speed or direction
     * 
     */
    STATIONARY;

    public String value() {
        return name();
    }

    public static TropicalCycloneMovementType fromValue(String v) {
        return valueOf(v);
    }

}
