//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.08 at 04:16:07 AM UTC 
//


package icao.iwxxm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import def.wmo.metce.TropicalCyclonePropertyType;


/**
 * <p>Java class for TropicalCycloneSIGMETType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TropicalCycloneSIGMETType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://icao.int/iwxxm/3.0}SIGMETType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tropicalCyclone" type="{http://def.wmo.int/metce/2013}TropicalCyclonePropertyType" maxOccurs="2" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TropicalCycloneSIGMETType", propOrder = {
    "tropicalCyclone"
})
public class TropicalCycloneSIGMETType
    extends SIGMETType
{

    protected List<TropicalCyclonePropertyType> tropicalCyclone;

    /**
     * Gets the value of the tropicalCyclone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tropicalCyclone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTropicalCyclone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TropicalCyclonePropertyType }
     * 
     * 
     */
    public List<TropicalCyclonePropertyType> getTropicalCyclone() {
        if (tropicalCyclone == null) {
            tropicalCyclone = new ArrayList<TropicalCyclonePropertyType>();
        }
        return this.tropicalCyclone;
    }

}
