//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.10 at 02:53:01 AM UTC 
//


package icao.iwxxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VolcanicAshSIGMETEvolvingConditionCollectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VolcanicAshSIGMETEvolvingConditionCollectionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://icao.int/iwxxm/3.0}SIGMETEvolvingConditionCollectionType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="volcanoId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VolcanicAshSIGMETEvolvingConditionCollectionType")
public class VolcanicAshSIGMETEvolvingConditionCollectionType
    extends SIGMETEvolvingConditionCollectionType
{

    @XmlAttribute(name = "volcanoId", required = true)
    protected String volcanoId;

    /**
     * Gets the value of the volcanoId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolcanoId() {
        return volcanoId;
    }

    /**
     * Sets the value of the volcanoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolcanoId(String value) {
        this.volcanoId = value;
    }

}
