//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.09 at 01:48:28 AM UTC 
//


package aero.aixm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AirspaceGeometryComponentPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AirspaceGeometryComponentPropertyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMPropertyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.aixm.aero/schema/5.1.1}AirspaceGeometryComponent"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AirspaceGeometryComponentPropertyType", propOrder = {
    "airspaceGeometryComponent"
})
public class AirspaceGeometryComponentPropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "AirspaceGeometryComponent", required = true)
    protected AirspaceGeometryComponentType airspaceGeometryComponent;

    /**
     * Gets the value of the airspaceGeometryComponent property.
     * 
     * @return
     *     possible object is
     *     {@link AirspaceGeometryComponentType }
     *     
     */
    public AirspaceGeometryComponentType getAirspaceGeometryComponent() {
        return airspaceGeometryComponent;
    }

    /**
     * Sets the value of the airspaceGeometryComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirspaceGeometryComponentType }
     *     
     */
    public void setAirspaceGeometryComponent(AirspaceGeometryComponentType value) {
        this.airspaceGeometryComponent = value;
    }

}
